# Generated by Django 4.0.4 on 2022-05-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=40, verbose_name='Категория навыка'),
        ),
    ]
