# Generated by Django 4.0.4 on 2022-05-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tag_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'hobby')},
        ),
    ]
