# Generated by Django 4.0.4 on 2022-05-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
    ]
