# Generated by Django 4.0.4 on 2022-06-02 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_profile_hobby_profile_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hobby',
            field=models.ManyToManyField(to='main.tag', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кандидат'),
        ),
    ]
