# Generated by Django 4.0.4 on 2022-06-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profile_hobby_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hobby',
            new_name='hobbies',
        ),
    ]
